sudo: required

language: python

services:
  - docker

before_install:
  - docker pull quay.io/tiramisu/mr.docs

script:
    - docker run --rm -v "${PWD}/docs":/build/docs:rw -u "$(id -u)":"$(id -g)" quay.io/tiramisu/mr.docs testhtml
    - docker run --rm -v "${PWD}/docs":/build/docs:rw -u "$(id -u)":"$(id -g)" quay.io/tiramisu/mr.docs linkcheck

